// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ReSys.Infrastructure.Persistence;

#nullable disable

namespace ReSys.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "example_status", new[] { "draft", "active", "archived" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReSys.Core.Domain.Testing.ExampleCategories.ExampleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_example_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_example_categories_name");

                    b.ToTable("example_categories", (string)null);
                });

            modelBuilder.Entity("ReSys.Core.Domain.Testing.Examples.Example", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HexColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("hex_color");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_examples");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_examples_category_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_examples_name");

                    b.ToTable("examples", (string)null);
                });

            modelBuilder.Entity("ReSys.Core.Domain.Testing.Examples.ExampleEmbedding", b =>
                {
                    b.Property<Guid>("ExampleId")
                        .HasColumnType("uuid")
                        .HasColumnName("example_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.HasKey("ExampleId")
                        .HasName("pk_example_embedding");

                    b.ToTable("example_embedding", (string)null);
                });

            modelBuilder.Entity("ReSys.Core.Domain.Testing.Examples.Example", b =>
                {
                    b.HasOne("ReSys.Core.Domain.Testing.ExampleCategories.ExampleCategory", "Category")
                        .WithMany("Examples")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_examples_example_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ReSys.Core.Domain.Testing.Examples.ExampleEmbedding", b =>
                {
                    b.HasOne("ReSys.Core.Domain.Testing.Examples.Example", "Example")
                        .WithOne("Embedding")
                        .HasForeignKey("ReSys.Core.Domain.Testing.Examples.ExampleEmbedding", "ExampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_example_embedding_examples_example_id");

                    b.Navigation("Example");
                });

            modelBuilder.Entity("ReSys.Core.Domain.Testing.ExampleCategories.ExampleCategory", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("ReSys.Core.Domain.Testing.Examples.Example", b =>
                {
                    b.Navigation("Embedding");
                });
#pragma warning restore 612, 618
        }
    }
}
